-- V003__insights.sql
-- Bổ sung table insights cho:
--   - Hero AI card on home screen (proactive AI announcements)
--   - Action cards generated from Intent 07 Analytics
-- Generated by worker-analytics (Phase 05) khi detect anomaly trong analytics_daily.
--
-- C17 Amendment (Phiên 8 2026-05-18 Path α): idx_insights_user_pending partial
-- index WHERE predicate dropped `AND expires_at > NOW()` clause. Postgres
-- requires functions in index predicate marked IMMUTABLE; NOW() is STABLE.
-- Fix: keep `status = 'pending'` filter only (IMMUTABLE — constant value).
-- Runtime queries must add `AND expires_at > NOW()` filter explicitly; index
-- still selective enough (status='pending' rare among insights). Parity với
-- V002:21 + V002:22 status-only partial indexes (same PG IMMUTABLE
-- constraint).
-- See decisions-log.md C17 amendment.

-- 1. INSIGHTS TABLE
CREATE TABLE insights (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Classification
  type          VARCHAR(60) NOT NULL,        
    -- 'REVENUE_DROP', 'REVENUE_SPIKE', 'STOCK_LOW', 'STOCK_OUT',
    -- 'TREND_SHIFT', 'TOP_SELLER_CHANGED', 'CATEGORY_DECLINE',
    -- 'PRICE_OUTLIER', 'NEW_OPPORTUNITY'
  severity      VARCHAR(20) NOT NULL DEFAULT 'info'
                  CHECK (severity IN ('info', 'warning', 'critical')),
  
  -- Display content (rendered directly by hero card / action card)
  label         VARCHAR(50) NOT NULL,         -- "AI VỪA PHÁT HIỆN"
  title         TEXT NOT NULL,                -- "Doanh thu tuần này giảm 12%"
  highlight     VARCHAR(50),                  -- "12%" — FE gradient amber
  description   TEXT NOT NULL,                -- "Tôi tìm ra 2 nguyên nhân chính..."
  
  -- Supporting data (for drill-down)
  data          JSONB NOT NULL DEFAULT '{}',
    -- {
    --   "period": "week",
    --   "delta_pct": -12.0,
    --   "current_value": 18500000,
    --   "previous_value": 21000000,
    --   "top_causes": ["cause1", "cause2"],
    --   "related_product_ids": [...]
    -- }
  
  -- Actions (JSONB array of {label, intent, payload})
  actions       JSONB NOT NULL DEFAULT '[]',
    -- [
    --   { "label": "Xem phân tích", "intent": "analyzing_by_voices", "payload": {...} },
    --   { "label": "Để sau", "intent": null, "payload": null }
    -- ]
  
  -- Lifecycle
  status        VARCHAR(20) NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'viewed', 'acted', 'dismissed', 'expired')),
  expires_at    TIMESTAMPTZ NOT NULL,         -- TTL, default NOW() + 7 days
  viewed_at     TIMESTAMPTZ,
  resolved_at   TIMESTAMPTZ,
  
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. INDEXES
-- Query pattern 1: "give me latest pending insight for hero card"
-- C17 Amendment (Phiên 8): expires_at > NOW() dropped from WHERE clause
-- (PG IMMUTABLE rule). Runtime query must filter expires_at > NOW() in
-- application SQL. Status='pending' filter still selective (most insights
-- transition pending → viewed/dismissed quickly).
CREATE INDEX idx_insights_user_pending
  ON insights(user_id, created_at DESC)
  WHERE status = 'pending';

-- Query pattern 2: "all insights for inbox tab"  
CREATE INDEX idx_insights_user_all
  ON insights(user_id, status, created_at DESC);

-- Query pattern 3: deduplication check (worker không spam cùng insight)
CREATE INDEX idx_insights_dedup
  ON insights(user_id, type, created_at DESC);

-- 3. COMMENTS
COMMENT ON TABLE insights IS 'Proactive AI announcements + analytics findings. Generated by worker-analytics. Consumed by hero card endpoint + inbox tab.';
COMMENT ON COLUMN insights.type IS 'Categorical, drives action template selection in worker';
COMMENT ON COLUMN insights.label IS 'Static UI prefix, e.g. "AI VỪA PHÁT HIỆN" or "GỢI Ý CHO ANH"';
COMMENT ON COLUMN insights.highlight IS 'Optional text chunk to render with gradient styling on FE';
COMMENT ON COLUMN insights.data IS 'Drill-down payload for analytics intent re-entry';
COMMENT ON COLUMN insights.actions IS 'Array of action buttons; each renders as CTA';

-- 4. SEED DATA (demo merchant for hackathon home screen)
-- Worker generates these realistically; seed này để FE có data render ngay
INSERT INTO insights (user_id, type, severity, label, title, highlight, description, data, actions, expires_at)
SELECT
  id,
  'REVENUE_DROP',
  'warning',
  'AI VỪA PHÁT HIỆN',
  'Doanh thu tuần này giảm 12%',
  '12%',
  'Tôi tìm ra 2 nguyên nhân chính. Anh xem thử nhé?',
  '{"period":"week","delta_pct":-12.0,"current_value":18500000,"previous_value":21000000}'::jsonb,
  '[
    {"label":"Xem phân tích","intent":"analyzing_by_voices","payload":{"focus":"revenue_drop_week"}},
    {"label":"Để sau","intent":null,"payload":null}
  ]'::jsonb,
  NOW() + INTERVAL '7 days'
FROM users
WHERE email = 'merchant@demo.com'
ON CONFLICT DO NOTHING;
